courses/urls.py
from django.conf.urls import url

from . import views

app_name = 'courses'
urlpatterns = [
    url(r'^$', views.courses, name='index'),
    url(r'courses$', views.courses, name='courses'),
    url(r'^(?P<course_id>[0-9]+)/$', views.detail, name='detail'),
]

professors/urls.py
from django.conf.urls import url

from . import views
app_name = 'professors'
urlpatterns = [
    url(r'^$', views.professors, name='index'),
    url(r'professors$', views.professors, name='professors'),
    url(r'^(?P<professor_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<professor_id>[0-9]+)/add_section$', views.add_section, name='add_section'),
    url(r'^(?P<professor_id>[0-9]+)/create_section$', views.create_section, name='create_section'),
]

school/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from professors import views

urlpatterns = [
    url(r'^$', views.professors),
    url(r'^professors/', include('professors.urls')),
    url(r'^courses/', include('courses.urls')),
    url(r'^sections/', include('sections.urls')),
    url(r'^admin/', admin.site.urls),
]

sections/urls.py
from django.conf.urls import url

from . import views

app_name = 'sections'
urlpatterns = [
    url(r'^$', views.sections, name='index'),
    url(r'sections$', views.sections, name='sections'),
    url(r'^(?P<section_id>[0-9]+)/delete$', views.delete, name='delete'),
]

courses/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=600)
    department = models.CharField(max_length=200)
    def __str__(self):
        return self.name

professors/models.py
from django.db import models

# Create your models here.
class Professor(models.Model):
    name = models.CharField(max_length=200)
    department = models.CharField(max_length=200)
    def __str__(self):
        return self.name

sections/models.py
from django.db import models

# Create your models here.
class Section(models.Model):
    professor = models.ForeignKey('professors.Professor', on_delete=models.CASCADE)
    course = models.ForeignKey('courses.Course', on_delete=models.CASCADE)
    time = models.TimeField()
    def __str__(self):
        return self.course.name + " taught by  " + self.professor.name + " @ " + self.time.__str__()

courses/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import Course
# Create your views here.
def courses(request):
    courses_list = Course.objects.order_by('-name')
    context = {
        'courses_list': courses_list,
    }
    return render(request, 'courses/index.html', context)

def detail(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    sections = course.section_set.all()
    context = {
        'course': course,
        'sections': sections,
    } 
    return render(request, 'courses/detail.html', context)
    

professors/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.http import HttpResponse
from django.template import loader
from .models import Professor
from courses.models import Course
from sections.models import Section
# Create your views here.

def professors(request):
    professors_list = Professor.objects.order_by('-name')
    context = {
        'professors_list': professors_list,
    }
    return render(request, 'professors/index.html', context)

def detail(request, professor_id):
    professor = get_object_or_404(Professor, pk=professor_id)
    sections = professor.section_set.all()
    return render(request, 'professors/detail.html', {'professor': professor, 'sections': sections})
    

def add_section(request, professor_id):
    professor = get_object_or_404(Professor, pk=professor_id)
    courses_list = Course.objects.all()
    context = {
        'professor': professor,
        'courses_list': courses_list,
    }
    return render(request, 'professors/create_section.html', context)
def create_section(request, professor_id):
    course= Course.objects.get(pk=request.POST['course_id'])
    professor = Professor.objects.get(pk=professor_id)
    time = request.POST['time']
    newSection = Section(professor= professor, course= course, time = time)
    newSection.save()
    return redirect('professors:detail', professor_id=professor_id)

sections/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from .models import Section
# Create your views here.
def sections(request):
    return HttpResponse("sections")
def delete(request, section_id):
    section = Section.objects.get(pk=section_id)
    professor_id = section.professor.id
    section.delete()
    return redirect('professors:detail', professor_id=professor_id) 

courses/templates/courses/detail.html
<h1>Course {{course.name}}</h1>

<p>
    <strong>Department</strong>
    {{ course.department }}
</p>

<p>
    <strong>Description</strong>
    {{ course.description }}
</p>

{% if sections %}
<h3>Sections</h3>
<ul>
    {% for section in sections %}
    <li>Taught by <a href="{% url 'professors:detail' section.professor.id %}">{{section.professor.name }}</a> at {{section.time}}</li>
    {% endfor %}
</ul>
{% endif %}

<a href="/courses">Back</a>

courses/templates/courses/index.html
<h1>Courses</h1>

{% if courses_list %}
<ul>
    {% for course in courses_list %}
    <li><a href="/courses/{{ course.id }}/">{{course.name}}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No courses are taught here.</p>
{% endif %}

professors/templates/professors/create_section.html
<h1>Create a Section</h1>
<p> Hello Professor {{professor.name}}. Select a course and time for your new section</p>


<form action="{% url 'professors:create_section' professor.id %}" method="post">
    {% csrf_token %}
    <select id="course_id" name="course_id">
        {% for course in courses_list %}
        <option value={{course.id}}>{{course.name}}</option>
        {% endfor %}
    </select>
    <input id="time" type="time" name="time"/>
    <input type ="submit" value="Create" />
</form>

professors/templates/professors/detail.html
<h1>Professor {{professor.name}}</h1>

<p>
    <strong>Department</strong>
    {{ professor.department }}
</p>

{% if sections %}
<h3>Sections</h3>
<ul>
    {% for section in sections %}
    <li>
        <a href="{% url 'courses:detail' section.course.id %}">{{section.course.name }}</a> at {{section.time}} | 
        <a href="{% url 'sections:delete' section.id %}">Drop this section</a>
    </li>
    {% endfor %}
</ul>
{% endif %}
<a href="{% url 'professors:add_section' professor.id %}">"Teach" a new section</a>
</br>
<a href="{% url 'professors:index' %}">Back</a>

professors/templates/professors/index.html
<h1>Professors</h1>

{% if professors_list %}
<ul>
    {% for professor in professors_list %}
    <li><a href="/professors/{{ professor.id }}/">{{professor.name}}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No Professors teach here.</p>
{% endif %}